const DYNAMIC_REDUCER_ATTACHED = "@@DYNAMIC_REDUCER/ATTACHED";
const DYNAMIC_REDUCER_INITIALSTATE = "@@DYNAMIC_REDUCER/INITIALSTATE";

export { DYNAMIC_REDUCER_ATTACHED, DYNAMIC_REDUCER_INITIALSTATE };
