const ATTACHABLE_REDUCER_ATTACHED = "@@ATTACHABLE_REDUCER/ATTACHED";
const ATTACHABLE_REDUCER_INITIALSTATE = "@@ATTACHABLE_REDUCER/INITIALSTATE";
const KEY_PARTS_SEPARATOR = ".";

export { ATTACHABLE_REDUCER_ATTACHED, ATTACHABLE_REDUCER_INITIALSTATE, KEY_PARTS_SEPARATOR };
