const ATTACHABLE_REDUCER_ATTACHED = "@@ATTACHABLE_REDUCER/ATTACHED";
const ATTACHABLE_REDUCER_INITIALSTATE = "@@ATTACHABLE_REDUCER/INITIALSTATE";

export { ATTACHABLE_REDUCER_ATTACHED, ATTACHABLE_REDUCER_INITIALSTATE };
